# Generated by Django 5.0.7 on 2024-07-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_contactform_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('list_message_permit', 'can see messages list')]},
        ),
    ]
