# Generated by Django 5.0.7 on 2024-07-16 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('account_permissions', 'can edit users account')]},
        ),
    ]
